### ISSUE TITLE
upload_file() does not work with python 3.4.2

### ISSUE THREAD

**Issue by baget** [randomchars/pushbullet.py#121]
the example of upload file using update_file() function does not work on python 3.4.2
if changing the python to 2.7.9 the same code works

the error that I'm getting:
```
Traceback (most recent call last):
  File "./sendpic.py", line 15, in <module>
    file_data = pb.upload_file(pic, "picture.jpg")
  File "/usr/local/lib/python3.4/dist-packages/pushbullet/pushbullet.py", line 203, in upload_file
    file_type = get_file_type(f, file_name)
  File "/usr/local/lib/python3.4/dist-packages/pushbullet/filetype.py", line 4, in _magic_get_file_type
    return file_type.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by tsvi** [comment]
This issue was fixed in 0.11
Please try upgrading and see if this is still an issue
